export const ADD_USER_OK_SAGA = "ADD_USER_OK_SAGA";
export const START_ADD_USER_SAGA = "START_ADD_USER_SAGA";
//
export const START_EDIT_USER_SAGA = "START_EDIT_USER_SAGA";
export const GET_TO_EDIT_USER_SAGA = "GET_TO_EDIT_USER_SAGA";
export const EDIT_USER_OK_SAGA = "EDIT_USER_OK_SAGA";

//
export const START_DELETE_USER_SAGA = "START_DELETE_USER_SAGA";
export const GET_TO_DELETE_USER_SAGA = "GET_TO_DELETE_USER_SAGA";
export const DELETE_USER_OK_SAGA = "DELETE_USER_OK_SAGA";

//
export const START_GET_USER_SAGA = "START_GET_USER_SAGA";
export const GET_USER_OK_SAGA = "GET_USER_OK_SAGA";
